### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by maximromanov** [PerseusDL/chronoplot#1]
The tool is great, so it makes sense to make it more universal:
- change "nisbas" to "category" (or something like that)

**Comment by maximromanov** [comment]
Types of lines: the names of lines in the drop-down should correspond to their names in D3 ("step-before"), for convenience.

**Comment by maximromanov** [comment]
Font style: "Lateef" for Arabic (or, maybe even everywhere). Separate style sheet?

**Comment by maximromanov** [comment]
Lines: shift of every next line added to the graph to avoid complete overlaps.
- shift up-right by the thickness of the line

**Comment by maximromanov** [comment]
BW version?
- is is possible to have a black and white version where the lines of the graph have different style (dotted, broken, squiggly, etc.)?

**Comment by maximromanov** [comment]
Dynamic sizing of the graph and the search panel? (% of the window size?)

**Comment by maximromanov** [comment]
Saving a graph into some reproducible format? Vector PDF?

**Comment by maximromanov** [comment]
Pop-up values, when hover over a point of a graph?

**Comment by caesarfeta** [comment]
I'm making these separate issues.
