### ISSUE TITLE
Can we also move the dataFile into config?

### ISSUE THREAD

**Issue by maximromanov** [PerseusDL/chronoplot#22]

**Comment by caesarfeta** [comment]
If I do that you won't be able to run chronoplot from the filesystem.  We'd have to find a home on a web-server.  The reason for this is loading files with Javascript after a webpage page is opened from the filesystem can't be done typically... security sandboxing.  If it wasn't in place I could write Javascript that when opened on someone's filesystem could read an important file on their computer, /etc/passwd for example, and save that data wherever I wanted.

**Comment by maximromanov** [comment]
Got it! Let's drop it then.
