### ISSUE TITLE
Different JSON format?

### ISSUE THREAD

**Issue by maximromanov** [PerseusDL/chronoplot#23]
It occurred to me that the current JSON format is not very efficient, since the same information is repeated too many times (Author's Name, Book title + transliteration), while the data that changes is actually very short (period and frequency). How difficult will it be to restructure the JSON---and Chronoplot---so that there is only one record for each book (now, it is---times the number of periods)? This will allow to reduce the data file size dramatically.

**Comment by caesarfeta** [comment]
Let's sit down and talk about it in person.  I think you're right.  When we started this it was just to use your existing data.  We didn't think at all about creating an optimal format.  Now is that time I guess ;)

**Comment by maximromanov** [comment]
Definitely! let's talk about this. Indeed we did not consider this, but now
my data is overinflated only because of the format. Any time today?

On Monday, October 27, 2014, Adam Tavares notifications@github.com wrote:

> Let's sit down and talk about it in person. I think you're right. When we
> started this it was just to use your existing data. We didn't think at all
> about creating an optimal format. Now is that time I guess ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PerseusDL/chronoplot/issues/23#issuecomment-60600701.

## 

Sincerely,
Maxim Romanov

Postdoctoral Associate
Department of Classics / Perseus Project
Tufts University
Email: maxim.romanov@tufts.edu
Personal site: www.alraqmiyyat.org

**Comment by caesarfeta** [comment]
metadata: {
    "JK157": {
        "timeseries": [[400,5],[600,4],[800,3]],
        "book": "",
        "description":"",
        "phonetic": "",
    }
}

**Comment by caesarfeta** [comment]
Waiting on data in new format.  Maxim will provide.

**Comment by caesarfeta** [comment]
https://github.com/PerseusDL/chronoplot/commit/08a1d00b45fcd1599390c416b47e36b708cab5c8
